# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RowSums <- function(x) {
    .Call('JAGUAR_RowSums', PACKAGE = 'JAGUAR', x)
}

RowMin <- function(x) {
    .Call('JAGUAR_RowMin', PACKAGE = 'JAGUAR', x)
}

scoreTest <- function(Eps, Tau, k, Y, snp) {
    .Call('JAGUAR_scoreTest', PACKAGE = 'JAGUAR', Eps, Tau, k, Y, snp)
}

snpOUT <- function(geno, Eps, Tau, k, Y) {
    .Call('JAGUAR_snpOUT', PACKAGE = 'JAGUAR', geno, Eps, Tau, k, Y)
}

GENEapply <- function(geno, Y, Eps, Tau, k) {
    .Call('JAGUAR_GENEapply', PACKAGE = 'JAGUAR', geno, Y, Eps, Tau, k)
}

gamma_test <- function(Eps, Tau, k, Y, snp) {
    .Call('JAGUAR_gamma_test', PACKAGE = 'JAGUAR', Eps, Tau, k, Y, snp)
}

jag_param <- function(Eps, Tau, k, Y, snp) {
    .Call('JAGUAR_jag_param', PACKAGE = 'JAGUAR', Eps, Tau, k, Y, snp)
}

getMinP <- function(mcMAT, Y, geno, Eps, Tau, k, v) {
    .Call('JAGUAR_getMinP', PACKAGE = 'JAGUAR', mcMAT, Y, geno, Eps, Tau, k, v)
}

