# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mc_scoreTest <- function(Eps, Tau, k, Y, snp, mcMAT) {
    .Call('JAGUAR_mc_scoreTest', PACKAGE = 'JAGUAR', Eps, Tau, k, Y, snp, mcMAT)
}

getMAX <- function(mcMAT, Y, geno, Eps, Tau, k) {
    .Call('JAGUAR_getMAX', PACKAGE = 'JAGUAR', mcMAT, Y, geno, Eps, Tau, k)
}

sim <- function(Eps, Tau, Eps_g, Tau_g, k, Y, Y_g, snp) {
    .Call('JAGUAR_sim', PACKAGE = 'JAGUAR', Eps, Tau, Eps_g, Tau_g, k, Y, Y_g, snp)
}

scoreTest <- function(Eps, Tau, k, Y, snp) {
    .Call('JAGUAR_scoreTest', PACKAGE = 'JAGUAR', Eps, Tau, k, Y, snp)
}

snpOUT <- function(geno, Eps, Tau, k, Y) {
    .Call('JAGUAR_snpOUT', PACKAGE = 'JAGUAR', geno, Eps, Tau, k, Y)
}

GENEapply <- function(geno, Y, Eps, Tau, k) {
    .Call('JAGUAR_GENEapply', PACKAGE = 'JAGUAR', geno, Y, Eps, Tau, k)
}

